package com.ns.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Notice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.isdelete
     *
     * @mbggenerated
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.createUser
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.projectName
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.opening_area
     *
     * @mbggenerated
     */
    private BigDecimal opening_area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.construction
     *
     * @mbggenerated
     */
    private String construction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.plot_ratio
     *
     * @mbggenerated
     */
    private String plot_ratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.total_area
     *
     * @mbggenerated
     */
    private BigDecimal total_area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.area_of_plot_ratio
     *
     * @mbggenerated
     */
    private BigDecimal area_of_plot_ratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.assessment
     *
     * @mbggenerated
     */
    private String assessment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.research
     *
     * @mbggenerated
     */
    private String research;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.project_summary
     *
     * @mbggenerated
     */
    private String project_summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.organization
     *
     * @mbggenerated
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.intention
     *
     * @mbggenerated
     */
    private String intention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.conditions
     *
     * @mbggenerated
     */
    private String conditions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.cooperation
     *
     * @mbggenerated
     */
    private String cooperation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.benefit
     *
     * @mbggenerated
     */
    private String benefit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.proportion
     *
     * @mbggenerated
     */
    private String proportion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.deadline
     *
     * @mbggenerated
     */
    private String deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.instruction
     *
     * @mbggenerated
     */
    private String instruction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.decision
     *
     * @mbggenerated
     */
    private String decision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.plot
     *
     * @mbggenerated
     */
    private String plot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.enterprise
     *
     * @mbggenerated
     */
    private String enterprise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.filename
     *
     * @mbggenerated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.payment
     *
     * @mbggenerated
     */
    private String payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.trading_terms
     *
     * @mbggenerated
     */
    private String trading_terms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.information
     *
     * @mbggenerated
     */
    private String information;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.complaint
     *
     * @mbggenerated
     */
    private String complaint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.weChat_official
     *
     * @mbggenerated
     */
    private String weChat_official;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.is_partner
     *
     * @mbggenerated
     */
    private String is_partner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.is_guarantee
     *
     * @mbggenerated
     */
    private String is_guarantee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.is_client
     *
     * @mbggenerated
     */
    private String is_client;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notice
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.isdelete
     *
     * @return the value of notice.isdelete
     *
     * @mbggenerated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.isdelete
     *
     * @param isdelete the value for notice.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.createtime
     *
     * @return the value of notice.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.createtime
     *
     * @param createtime the value for notice.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.createUser
     *
     * @return the value of notice.createUser
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.createUser
     *
     * @param createUser the value for notice.createUser
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.projectName
     *
     * @return the value of notice.projectName
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.projectName
     *
     * @param projectName the value for notice.projectName
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.opening_area
     *
     * @return the value of notice.opening_area
     *
     * @mbggenerated
     */
    public BigDecimal getOpening_area() {
        return opening_area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.opening_area
     *
     * @param opening_area the value for notice.opening_area
     *
     * @mbggenerated
     */
    public void setOpening_area(BigDecimal opening_area) {
        this.opening_area = opening_area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.construction
     *
     * @return the value of notice.construction
     *
     * @mbggenerated
     */
    public String getConstruction() {
        return construction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.construction
     *
     * @param construction the value for notice.construction
     *
     * @mbggenerated
     */
    public void setConstruction(String construction) {
        this.construction = construction == null ? null : construction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.plot_ratio
     *
     * @return the value of notice.plot_ratio
     *
     * @mbggenerated
     */
    public String getPlot_ratio() {
        return plot_ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.plot_ratio
     *
     * @param plot_ratio the value for notice.plot_ratio
     *
     * @mbggenerated
     */
    public void setPlot_ratio(String plot_ratio) {
        this.plot_ratio = plot_ratio == null ? null : plot_ratio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.total_area
     *
     * @return the value of notice.total_area
     *
     * @mbggenerated
     */
    public BigDecimal getTotal_area() {
        return total_area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.total_area
     *
     * @param total_area the value for notice.total_area
     *
     * @mbggenerated
     */
    public void setTotal_area(BigDecimal total_area) {
        this.total_area = total_area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.area_of_plot_ratio
     *
     * @return the value of notice.area_of_plot_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getArea_of_plot_ratio() {
        return area_of_plot_ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.area_of_plot_ratio
     *
     * @param area_of_plot_ratio the value for notice.area_of_plot_ratio
     *
     * @mbggenerated
     */
    public void setArea_of_plot_ratio(BigDecimal area_of_plot_ratio) {
        this.area_of_plot_ratio = area_of_plot_ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.assessment
     *
     * @return the value of notice.assessment
     *
     * @mbggenerated
     */
    public String getAssessment() {
        return assessment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.assessment
     *
     * @param assessment the value for notice.assessment
     *
     * @mbggenerated
     */
    public void setAssessment(String assessment) {
        this.assessment = assessment == null ? null : assessment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.research
     *
     * @return the value of notice.research
     *
     * @mbggenerated
     */
    public String getResearch() {
        return research;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.research
     *
     * @param research the value for notice.research
     *
     * @mbggenerated
     */
    public void setResearch(String research) {
        this.research = research == null ? null : research.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.source
     *
     * @return the value of notice.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.source
     *
     * @param source the value for notice.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.project_summary
     *
     * @return the value of notice.project_summary
     *
     * @mbggenerated
     */
    public String getProject_summary() {
        return project_summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.project_summary
     *
     * @param project_summary the value for notice.project_summary
     *
     * @mbggenerated
     */
    public void setProject_summary(String project_summary) {
        this.project_summary = project_summary == null ? null : project_summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.organization
     *
     * @return the value of notice.organization
     *
     * @mbggenerated
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.organization
     *
     * @param organization the value for notice.organization
     *
     * @mbggenerated
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.intention
     *
     * @return the value of notice.intention
     *
     * @mbggenerated
     */
    public String getIntention() {
        return intention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.intention
     *
     * @param intention the value for notice.intention
     *
     * @mbggenerated
     */
    public void setIntention(String intention) {
        this.intention = intention == null ? null : intention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.conditions
     *
     * @return the value of notice.conditions
     *
     * @mbggenerated
     */
    public String getConditions() {
        return conditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.conditions
     *
     * @param conditions the value for notice.conditions
     *
     * @mbggenerated
     */
    public void setConditions(String conditions) {
        this.conditions = conditions == null ? null : conditions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.cooperation
     *
     * @return the value of notice.cooperation
     *
     * @mbggenerated
     */
    public String getCooperation() {
        return cooperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.cooperation
     *
     * @param cooperation the value for notice.cooperation
     *
     * @mbggenerated
     */
    public void setCooperation(String cooperation) {
        this.cooperation = cooperation == null ? null : cooperation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.benefit
     *
     * @return the value of notice.benefit
     *
     * @mbggenerated
     */
    public String getBenefit() {
        return benefit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.benefit
     *
     * @param benefit the value for notice.benefit
     *
     * @mbggenerated
     */
    public void setBenefit(String benefit) {
        this.benefit = benefit == null ? null : benefit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.proportion
     *
     * @return the value of notice.proportion
     *
     * @mbggenerated
     */
    public String getProportion() {
        return proportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.proportion
     *
     * @param proportion the value for notice.proportion
     *
     * @mbggenerated
     */
    public void setProportion(String proportion) {
        this.proportion = proportion == null ? null : proportion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.deadline
     *
     * @return the value of notice.deadline
     *
     * @mbggenerated
     */
    public String getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.deadline
     *
     * @param deadline the value for notice.deadline
     *
     * @mbggenerated
     */
    public void setDeadline(String deadline) {
        this.deadline = deadline == null ? null : deadline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.instruction
     *
     * @return the value of notice.instruction
     *
     * @mbggenerated
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.instruction
     *
     * @param instruction the value for notice.instruction
     *
     * @mbggenerated
     */
    public void setInstruction(String instruction) {
        this.instruction = instruction == null ? null : instruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.decision
     *
     * @return the value of notice.decision
     *
     * @mbggenerated
     */
    public String getDecision() {
        return decision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.decision
     *
     * @param decision the value for notice.decision
     *
     * @mbggenerated
     */
    public void setDecision(String decision) {
        this.decision = decision == null ? null : decision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.plot
     *
     * @return the value of notice.plot
     *
     * @mbggenerated
     */
    public String getPlot() {
        return plot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.plot
     *
     * @param plot the value for notice.plot
     *
     * @mbggenerated
     */
    public void setPlot(String plot) {
        this.plot = plot == null ? null : plot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.enterprise
     *
     * @return the value of notice.enterprise
     *
     * @mbggenerated
     */
    public String getEnterprise() {
        return enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.enterprise
     *
     * @param enterprise the value for notice.enterprise
     *
     * @mbggenerated
     */
    public void setEnterprise(String enterprise) {
        this.enterprise = enterprise == null ? null : enterprise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.filename
     *
     * @return the value of notice.filename
     *
     * @mbggenerated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.filename
     *
     * @param filename the value for notice.filename
     *
     * @mbggenerated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.payment
     *
     * @return the value of notice.payment
     *
     * @mbggenerated
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.payment
     *
     * @param payment the value for notice.payment
     *
     * @mbggenerated
     */
    public void setPayment(String payment) {
        this.payment = payment == null ? null : payment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.trading_terms
     *
     * @return the value of notice.trading_terms
     *
     * @mbggenerated
     */
    public String getTrading_terms() {
        return trading_terms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.trading_terms
     *
     * @param trading_terms the value for notice.trading_terms
     *
     * @mbggenerated
     */
    public void setTrading_terms(String trading_terms) {
        this.trading_terms = trading_terms == null ? null : trading_terms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.information
     *
     * @return the value of notice.information
     *
     * @mbggenerated
     */
    public String getInformation() {
        return information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.information
     *
     * @param information the value for notice.information
     *
     * @mbggenerated
     */
    public void setInformation(String information) {
        this.information = information == null ? null : information.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.complaint
     *
     * @return the value of notice.complaint
     *
     * @mbggenerated
     */
    public String getComplaint() {
        return complaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.complaint
     *
     * @param complaint the value for notice.complaint
     *
     * @mbggenerated
     */
    public void setComplaint(String complaint) {
        this.complaint = complaint == null ? null : complaint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.fax
     *
     * @return the value of notice.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.fax
     *
     * @param fax the value for notice.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.url
     *
     * @return the value of notice.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.url
     *
     * @param url the value for notice.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.weChat_official
     *
     * @return the value of notice.weChat_official
     *
     * @mbggenerated
     */
    public String getWeChat_official() {
        return weChat_official;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.weChat_official
     *
     * @param weChat_official the value for notice.weChat_official
     *
     * @mbggenerated
     */
    public void setWeChat_official(String weChat_official) {
        this.weChat_official = weChat_official == null ? null : weChat_official.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.address
     *
     * @return the value of notice.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.address
     *
     * @param address the value for notice.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.is_partner
     *
     * @return the value of notice.is_partner
     *
     * @mbggenerated
     */
    public String getIs_partner() {
        return is_partner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.is_partner
     *
     * @param is_partner the value for notice.is_partner
     *
     * @mbggenerated
     */
    public void setIs_partner(String is_partner) {
        this.is_partner = is_partner == null ? null : is_partner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.is_guarantee
     *
     * @return the value of notice.is_guarantee
     *
     * @mbggenerated
     */
    public String getIs_guarantee() {
        return is_guarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.is_guarantee
     *
     * @param is_guarantee the value for notice.is_guarantee
     *
     * @mbggenerated
     */
    public void setIs_guarantee(String is_guarantee) {
        this.is_guarantee = is_guarantee == null ? null : is_guarantee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.is_client
     *
     * @return the value of notice.is_client
     *
     * @mbggenerated
     */
    public String getIs_client() {
        return is_client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.is_client
     *
     * @param is_client the value for notice.is_client
     *
     * @mbggenerated
     */
    public void setIs_client(String is_client) {
        this.is_client = is_client == null ? null : is_client.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Notice other = (Notice) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIsdelete() == null ? other.getIsdelete() == null : this.getIsdelete().equals(other.getIsdelete()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getProjectName() == null ? other.getProjectName() == null : this.getProjectName().equals(other.getProjectName()))
            && (this.getOpening_area() == null ? other.getOpening_area() == null : this.getOpening_area().equals(other.getOpening_area()))
            && (this.getConstruction() == null ? other.getConstruction() == null : this.getConstruction().equals(other.getConstruction()))
            && (this.getPlot_ratio() == null ? other.getPlot_ratio() == null : this.getPlot_ratio().equals(other.getPlot_ratio()))
            && (this.getTotal_area() == null ? other.getTotal_area() == null : this.getTotal_area().equals(other.getTotal_area()))
            && (this.getArea_of_plot_ratio() == null ? other.getArea_of_plot_ratio() == null : this.getArea_of_plot_ratio().equals(other.getArea_of_plot_ratio()))
            && (this.getAssessment() == null ? other.getAssessment() == null : this.getAssessment().equals(other.getAssessment()))
            && (this.getResearch() == null ? other.getResearch() == null : this.getResearch().equals(other.getResearch()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
            && (this.getProject_summary() == null ? other.getProject_summary() == null : this.getProject_summary().equals(other.getProject_summary()))
            && (this.getOrganization() == null ? other.getOrganization() == null : this.getOrganization().equals(other.getOrganization()))
            && (this.getIntention() == null ? other.getIntention() == null : this.getIntention().equals(other.getIntention()))
            && (this.getConditions() == null ? other.getConditions() == null : this.getConditions().equals(other.getConditions()))
            && (this.getCooperation() == null ? other.getCooperation() == null : this.getCooperation().equals(other.getCooperation()))
            && (this.getBenefit() == null ? other.getBenefit() == null : this.getBenefit().equals(other.getBenefit()))
            && (this.getProportion() == null ? other.getProportion() == null : this.getProportion().equals(other.getProportion()))
            && (this.getDeadline() == null ? other.getDeadline() == null : this.getDeadline().equals(other.getDeadline()))
            && (this.getInstruction() == null ? other.getInstruction() == null : this.getInstruction().equals(other.getInstruction()))
            && (this.getDecision() == null ? other.getDecision() == null : this.getDecision().equals(other.getDecision()))
            && (this.getPlot() == null ? other.getPlot() == null : this.getPlot().equals(other.getPlot()))
            && (this.getEnterprise() == null ? other.getEnterprise() == null : this.getEnterprise().equals(other.getEnterprise()))
            && (this.getFilename() == null ? other.getFilename() == null : this.getFilename().equals(other.getFilename()))
            && (this.getPayment() == null ? other.getPayment() == null : this.getPayment().equals(other.getPayment()))
            && (this.getTrading_terms() == null ? other.getTrading_terms() == null : this.getTrading_terms().equals(other.getTrading_terms()))
            && (this.getInformation() == null ? other.getInformation() == null : this.getInformation().equals(other.getInformation()))
            && (this.getComplaint() == null ? other.getComplaint() == null : this.getComplaint().equals(other.getComplaint()))
            && (this.getFax() == null ? other.getFax() == null : this.getFax().equals(other.getFax()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getWeChat_official() == null ? other.getWeChat_official() == null : this.getWeChat_official().equals(other.getWeChat_official()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getIs_partner() == null ? other.getIs_partner() == null : this.getIs_partner().equals(other.getIs_partner()))
            && (this.getIs_guarantee() == null ? other.getIs_guarantee() == null : this.getIs_guarantee().equals(other.getIs_guarantee()))
            && (this.getIs_client() == null ? other.getIs_client() == null : this.getIs_client().equals(other.getIs_client()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIsdelete() == null) ? 0 : getIsdelete().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getProjectName() == null) ? 0 : getProjectName().hashCode());
        result = prime * result + ((getOpening_area() == null) ? 0 : getOpening_area().hashCode());
        result = prime * result + ((getConstruction() == null) ? 0 : getConstruction().hashCode());
        result = prime * result + ((getPlot_ratio() == null) ? 0 : getPlot_ratio().hashCode());
        result = prime * result + ((getTotal_area() == null) ? 0 : getTotal_area().hashCode());
        result = prime * result + ((getArea_of_plot_ratio() == null) ? 0 : getArea_of_plot_ratio().hashCode());
        result = prime * result + ((getAssessment() == null) ? 0 : getAssessment().hashCode());
        result = prime * result + ((getResearch() == null) ? 0 : getResearch().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getProject_summary() == null) ? 0 : getProject_summary().hashCode());
        result = prime * result + ((getOrganization() == null) ? 0 : getOrganization().hashCode());
        result = prime * result + ((getIntention() == null) ? 0 : getIntention().hashCode());
        result = prime * result + ((getConditions() == null) ? 0 : getConditions().hashCode());
        result = prime * result + ((getCooperation() == null) ? 0 : getCooperation().hashCode());
        result = prime * result + ((getBenefit() == null) ? 0 : getBenefit().hashCode());
        result = prime * result + ((getProportion() == null) ? 0 : getProportion().hashCode());
        result = prime * result + ((getDeadline() == null) ? 0 : getDeadline().hashCode());
        result = prime * result + ((getInstruction() == null) ? 0 : getInstruction().hashCode());
        result = prime * result + ((getDecision() == null) ? 0 : getDecision().hashCode());
        result = prime * result + ((getPlot() == null) ? 0 : getPlot().hashCode());
        result = prime * result + ((getEnterprise() == null) ? 0 : getEnterprise().hashCode());
        result = prime * result + ((getFilename() == null) ? 0 : getFilename().hashCode());
        result = prime * result + ((getPayment() == null) ? 0 : getPayment().hashCode());
        result = prime * result + ((getTrading_terms() == null) ? 0 : getTrading_terms().hashCode());
        result = prime * result + ((getInformation() == null) ? 0 : getInformation().hashCode());
        result = prime * result + ((getComplaint() == null) ? 0 : getComplaint().hashCode());
        result = prime * result + ((getFax() == null) ? 0 : getFax().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getWeChat_official() == null) ? 0 : getWeChat_official().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getIs_partner() == null) ? 0 : getIs_partner().hashCode());
        result = prime * result + ((getIs_guarantee() == null) ? 0 : getIs_guarantee().hashCode());
        result = prime * result + ((getIs_client() == null) ? 0 : getIs_client().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", createtime=").append(createtime);
        sb.append(", createUser=").append(createUser);
        sb.append(", projectName=").append(projectName);
        sb.append(", opening_area=").append(opening_area);
        sb.append(", construction=").append(construction);
        sb.append(", plot_ratio=").append(plot_ratio);
        sb.append(", total_area=").append(total_area);
        sb.append(", area_of_plot_ratio=").append(area_of_plot_ratio);
        sb.append(", assessment=").append(assessment);
        sb.append(", research=").append(research);
        sb.append(", source=").append(source);
        sb.append(", project_summary=").append(project_summary);
        sb.append(", organization=").append(organization);
        sb.append(", intention=").append(intention);
        sb.append(", conditions=").append(conditions);
        sb.append(", cooperation=").append(cooperation);
        sb.append(", benefit=").append(benefit);
        sb.append(", proportion=").append(proportion);
        sb.append(", deadline=").append(deadline);
        sb.append(", instruction=").append(instruction);
        sb.append(", decision=").append(decision);
        sb.append(", plot=").append(plot);
        sb.append(", enterprise=").append(enterprise);
        sb.append(", filename=").append(filename);
        sb.append(", payment=").append(payment);
        sb.append(", trading_terms=").append(trading_terms);
        sb.append(", information=").append(information);
        sb.append(", complaint=").append(complaint);
        sb.append(", fax=").append(fax);
        sb.append(", url=").append(url);
        sb.append(", weChat_official=").append(weChat_official);
        sb.append(", address=").append(address);
        sb.append(", is_partner=").append(is_partner);
        sb.append(", is_guarantee=").append(is_guarantee);
        sb.append(", is_client=").append(is_client);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}